name: Python Checks with Ruff and Tests 2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.14]  # Test against multiple Python versions

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies and Ruff
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff  # Install pytest for testing, Ruff for linting
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Ruff Linting
      - name: Run Ruff Linting
        run: |
          ruff .

      # Step 5: Run Tests
      - name: Run Pytest Tests
        run: |
          pytest