name: Python Checks with Ruff and Tests

on:
  push:
    branches:
      - main  # Trigger workflow when code is pushed to `main`
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests to `main`

jobs:
  lint-and-test:
    name: Lint and Run Tests
    runs-on: ubuntu-latest  # Use Ubuntu virtual machine

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Valid Python versions

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies (if `requirements.txt` exists)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Ruff Linting
      - name: Run Ruff Linting
        run: |
          ruff .

      # Step 5: Run Tests
      - name: Run Pytest Tests
        run: |
          pytest